name: Deploy Intranet to WordPress Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to Server
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🚀 Sync files via LFTP
      run: |
        lftp -c "set ftp:ssl-allow no; set ftp:passive-mode true; open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' '${{ secrets.FTP_SERVER }}'; mirror -R --parallel=5 --exclude-glob '.git*' --exclude-glob 'README.md' --exclude-glob 'download.ps1' --exclude-glob 'intranet-implatec.zip' ./ '${{ secrets.FTP_REMOTE_DIR }}'"
